### ISSUE TITLE
Unable to download open-images dataset using cm framework.

### ISSUE THREAD

**Issue by michaelclesi** [mlcommons/ck#595] opened 2022-12-22 21:55 UTC
Hello, [using this tutorial link](https://github.com/mlcommons/ck/blob/master/docs/tutorials/sc22-scc-mlperf.md) and on RHEL 8.5.

Running this script:

`cm run script "get preprocessed dataset object-detection open-images _validation _500 _NCHW"`

Returns this log file:

```
[mclesi2@hpc]$ cm run script "get preprocessed dataset object-detection open-images _validation _500 _NCHW"

* Searching for collective script(s) with tags "get,preprocessed,dataset,object-detection,open-images" and variations "validation,500,NCHW"
  - Number of scripts found: 1
  - Searching for cached script outputs with the following tags: -tmp,get,preprocessed,dataset,object-detection,open-images
    - Number of cached script outputs found: 0
  - Found script::get-preprocessed-dataset-openimages,9842f1be8cba4c7b in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-preprocessed-dataset-openimages
    Prepared variations: _validation,_500,_NCHW,_fp32
  - Creating new "cache" script artifact in the CM local repository ...
    - Tags: tmp,get,preprocessed,dataset,object-detection,open-images,openimages,_validation,_500,_NCHW,_fp32,script-artifact-9842f1be8cba4c7b
  - Changing to /project/mclesi2/CM/repos/local/cache/8c7c86ca401a443d
  - Checking dependencies on other CM scripts:

    * Searching for collective script(s) with tags "get,python3"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,get,python3
        - Number of cached script outputs found: 1
      - Found script::get-python3,d0b5dd74373f4a62 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-python3
        - Found cached script output: /project/mclesi2/CM/repos/local/cache/f2c0a8941c2740cb
        - Checking prehook dependencies on other CM scripts:
          - Loading state from cached entry ...
        - Checking posthook dependencies on other CM scripts:
        - Checking post dependencies on other CM scripts:
      - running time of script "get,python,python3,get-python,get-python3": 0.35 sec.

    * Searching for collective script(s) with tags "get,dataset,object-detection,openimages,original" and variations "validation,500"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,get,dataset,object-detection,openimages,original
        - Number of cached script outputs found: 1
      - Found script::get-dataset-openimages,0a9d49b644cf4142 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-dataset-openimages
        Prepared variations: _validation,_500
        - Found cached script output: /project/mclesi2/CM/repos/local/cache/ed32883a518e4b50
      - Checking dynamic dependencies on other CM scripts:
      - Processing env after dependencies ...
        - Checking prehook dependencies on other CM scripts:
          - Loading state from cached entry ...
        - Checking posthook dependencies on other CM scripts:
        - Checking post dependencies on other CM scripts:
      - running time of script "get,dataset,openimages,open-images,object-detection,original": 0.28 sec.

    * Searching for collective script(s) with tags "mlperf,mlcommons,inference,source,src"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,mlperf,mlcommons,inference,source,src
        - Number of cached script outputs found: 2
      - Found script::get-mlperf-inference-src,4b57186581024797 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-mlperf-inference-src
        Prepared variations: _default,_short-history
        - Found cached script output: /project/mclesi2/CM/repos/local/cache/3b9bc43213334532
      - Checking dynamic dependencies on other CM scripts:
      - Processing env after dependencies ...
        - Checking prehook dependencies on other CM scripts:
          - Loading state from cached entry ...
        - Checking posthook dependencies on other CM scripts:
        - Checking post dependencies on other CM scripts:
      - running time of script "get,src,source,inference,inference-src,inference-source,mlperf,mlcommons": 0.33 sec.

    * Searching for collective script(s) with tags "get,generic-python-lib" and variations "pycocotools"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib
        - Number of cached script outputs found: 8
      - Found script::get-generic-python-lib,94b62a682bc44791 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-generic-python-lib
        Prepared variations: _pycocotools
        - Found cached script output: /project/mclesi2/CM/repos/local/cache/1a307e2668a3410e
      - Checking dynamic dependencies on other CM scripts:
      - Processing env after dependencies ...
        - Checking prehook dependencies on other CM scripts:
          - Loading state from cached entry ...
        - Checking posthook dependencies on other CM scripts:
        - Checking post dependencies on other CM scripts:
      - running time of script "get,generic,generic-python-lib": 0.26 sec.

    * Searching for collective script(s) with tags "get,generic-python-lib" and variations "opencv-python"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib
        - Number of cached script outputs found: 8
      - Found script::get-generic-python-lib,94b62a682bc44791 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-generic-python-lib
        Prepared variations: _opencv-python
        - Found cached script output: /project/mclesi2/CM/repos/local/cache/e2e265e48ba84253
      - Checking dynamic dependencies on other CM scripts:
      - Processing env after dependencies ...
        - Checking prehook dependencies on other CM scripts:
          - Loading state from cached entry ...
        - Checking posthook dependencies on other CM scripts:
        - Checking post dependencies on other CM scripts:
      - running time of script "get,generic,generic-python-lib": 0.28 sec.

    * Searching for collective script(s) with tags "get,generic-python-lib" and variations "pillow"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib
        - Number of cached script outputs found: 8
      - Found script::get-generic-python-lib,94b62a682bc44791 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-generic-python-lib
        Prepared variations: _pillow
        - Found cached script output: /project/mclesi2/CM/repos/local/cache/46739d3e8b324061
      - Checking dynamic dependencies on other CM scripts:
      - Processing env after dependencies ...
        - Checking prehook dependencies on other CM scripts:
          - Loading state from cached entry ...
        - Checking posthook dependencies on other CM scripts:
        - Checking post dependencies on other CM scripts:
      - running time of script "get,generic,generic-python-lib": 0.26 sec.

    * Searching for collective script(s) with tags "get,generic-python-lib" and variations "numpy"
      - Number of scripts found: 1
      - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib
        - Number of cached script outputs found: 8
      - Found script::get-generic-python-lib,94b62a682bc44791 in /project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-generic-python-lib
        Prepared variations: _numpy
        - Found cached script output: /project/mclesi2/CM/repos/local/cache/47dc1e0088bc4930
      - Checking dynamic dependencies on other CM scripts:
      - Processing env after dependencies ...
        - Checking prehook dependencies on other CM scripts:
          - Loading state from cached entry ...
        - Checking posthook dependencies on other CM scripts:
        - Checking post dependencies on other CM scripts:
      - running time of script "get,generic,generic-python-lib": 0.27 sec.
  - Processing env after dependencies ...
  - Running preprocess ...
Using MLCommons Inference source from '/ddnA/project/lyan1/mclesi2/CM/repos/local/cache/3b9bc43213334532/inference'

  - Running native script "/project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-preprocessed-dataset-openimages/run.sh" from temporal script "tmp-run.sh" in "/ddnA/project/lyan1/mclesi2/CM/repos/local/cache/8c7c86ca401a443d" ...

ERROR:coco:no images in image list found
Traceback (most recent call last):
  File "/project/mclesi2/CM/repos/mlcommons@ck/cm-mlops/script/get-preprocessed-dataset-openimages/preprocess.py", line 21, in <module>
    openimages.OpenImages(data_path=dataset_path,
  File "/ddnA/project/lyan1/mclesi2/CM/repos/local/cache/3b9bc43213334532/inference/vision/classification_and_detection/python/openimages.py", line 112, in __init__
    raise ValueError("no images in image list found")
ValueError: no images in image list found

CM error: Portable CM script failed (name = get-preprocessed-dataset-openimages, return code = 256)

Note that it is often a portability problem of the third-party tool or native script that is wrapped and unified by this CM script.
The CM concept is to collaboratively fix such issues inside portable CM scripts to make existing tools and native script more portable, interoperable, deterministic and reproducible.

Please help the community by reporting the full log with the command line here:
* https://github.com/mlcommons/ck/issues
* https://bit.ly/mlperf-edu-wg

Thank you!
```
Apologies in advance! My first issue report, not sure of the nomenclature I aught to use for this.

**Comment by arjunsuresh** [comment] 2022-12-22 23:32
Hi @michaelclesi , this error is because [our PR](https://github.com/mlcommons/inference/pull/1297) is not yet accepted in the inference repo which unfortunately had a non-backward compatible change which was unavoidable.

Can you please update your command like below for now (to use the octoml inference branch)?

```
cm run script "get preprocessed dataset object-detection open-images _validation _500 _NCHW"   --adr.inference-src.tags=_octoml
```

**Comment by arjunsuresh** [comment] 2022-12-23 11:19
Hi @michaelclesi Thankfully our PR just got merged in the inference repo. So you can just do the following command to clean the local cache and then the previous commands should work
```
cm rm cache --tags=mlperf,inference,src -f
```

**Comment by gfursin** [comment] 2022-12-23 11:31
> Hi @michaelclesi Thankfully our PR just got merged in the inference repo. So you can just do the following command to clean the local cache and then the previous commands should work
> 
> ```
> cm rm cache --tags=mlperf,inference,src -f
> ```

Also, just in case, you can get the latest version of the CM automation recipes as follows:
```
cm pull repo mlcommons@ck
```

The MLCommons taskforce on education and reproducibility is updating them every week based on the user feedback and the roadmap to automate design space exploration of ML Systems...

**Comment by gfursin** [comment] 2023-01-03 10:38
Happy New Year, @michaelclesi. Can we close this ticket? Thanks!

**Closed** 2023-01-03 20:14 UTC
