### ISSUE TITLE
Error trying to preprocess imagenet with OpenCV on Raspberry Pi 4 

### ISSUE THREAD

**Issue by slahiruk** [mlcommons/ck#172] opened 2021-09-07 09:52 UTC
Just posting a ck issue that I have encountered. I am following the instructions in as in this file [README.md](https://github.com/mlcommons/ck/files/7120576/README.md)

When running this command (without `time`)
``` 
time ck install package --dep_add_tags.dataset-source=full \                                
          --tags=dataset,imagenet,val,full,preprocessed,using-opencv,side.224 \             
          --version=2012 
```

I get this error

```
Traceback (most recent call last):
File "/home/ubuntu/CK/local/venv/mlperf-inference/CK/ck-mlops/package/dataset-imagenet-preprocessed-using-opencv/preprocess_image_dataset.py", line 192, in <module>
    assert len(selected_filenames) == volume
NameError: name 'selected_filenames' is not defined
```

System specs
```
Raspberry Pi 4
Ubuntu 20.04.1
Python 3.8.5
```

**Comment by gfursin** [comment] 2021-09-07 10:07
Thank you very much for your report, @slahiruk! Let me check it!

**Comment by gfursin** [comment] 2021-09-15 09:40
Hi @slahiruk - I can't reproduce your issue. It seems to be working on my platforms fine. 

My feeling is that your ImageNet datasets is not complete or broken.

By the way, I updated the reproducibility reports. My suggestion is to take this report, redo the steps and provide the full log (including how you detect ImageNet and what is inside that directory):
* https://github.com/mlcommons/ck/blob/master/docs/mlperf-automation/reproduce/ck-6582273dd3646e28.md

If it doesn't work out. Let's have a conf-call to debug it together. Thank you!

**Comment by gfursin** [comment] 2021-09-15 09:44
By the way, if you look at the code in "/home/ubuntu/CK/local/venv/mlperf-inference/CK/ck-mlops/package/dataset-imagenet-preprocessed-using-opencv/preprocess_image_dataset.py", it seems that "source_dir" doesn't exist while it should be pointing to the ImageNet ...

**Comment by gfursin** [comment] 2021-10-06 10:03
Closing due to no feedback.

**Closed by gfursin** 2021-10-06 10:03 UTC
Labels: bug, question, waiting for user input
